#ifndef IOT_MICRO_FIRMWARE_SRC_LOCAL_COMMAND_MANAGER_INCLUDE_LOCAL_COMMAND_MANAGER_LOCAL_COMMAND_OBSERVER_H_
#define IOT_MICRO_FIRMWARE_SRC_LOCAL_COMMAND_MANAGER_INCLUDE_LOCAL_COMMAND_MANAGER_LOCAL_COMMAND_OBSERVER_H_

class local_command_observer
{
public:
    virtual int process_command() = 0;
    virtual ~local_command_observer() {}
};

#endif // IOT_MICRO_FIRMWARE_SRC_LOCAL_COMMAND_MANAGER_INCLUDE_LOCAL_COMMAND_MANAGER_LOCAL_COMMAND_OBSERVER_H_
