#ifndef IOT_MICRO_FIRMWARE_SRC_TRANSPORT_MANAGER_INCLUDE_TRANSPORT_MANAGER_TRANSPORT_MANAGER_H_
#define IOT_MICRO_FIRMWARE_SRC_TRANSPORT_MANAGER_INCLUDE_TRANSPORT_MANAGER_TRANSPORT_MANAGER_H_

class TransportManager{
    public:
        TransportManager();

        int Connect();
        
    private:
    };

#endif  // IOT_MICRO_FIRMWARE_SRC_TRANSPORT_MANAGER_INCLUDE_TRANSPORT_MANAGER_TRANSPORT_MANAGER_H_
