#ifndef IOT_MICRO_FIRMWARE_SRC_REMOTE_COMMAND_MANAGER_INCLUDE_REMOTE_COMMAND_MANAGER_REMOTE_COMMAND_OBSERVER_H_
#define IOT_MICRO_FIRMWARE_SRC_REMOTE_COMMAND_MANAGER_INCLUDE_REMOTE_COMMAND_MANAGER_REMOTE_COMMAND_OBSERVER_H_

class remote_command_observer
{
public:
    virtual int process_command() = 0;
    virtual ~remote_command_observer() {}
};

#endif // IOT_MICRO_FIRMWARE_SRC_REMOTE_COMMAND_MANAGER_INCLUDE_REMOTE_COMMAND_MANAGER_REMOTE_COMMAND_OBSERVER_H_
