@startuml
!include <C4/C4_Component>

AddRelTag("invisible", $textColor="transparent", $lineColor="transparent", $lineStyle = DashedLine())

title C4 Component Diagram for Communications Sender
'----------------------------------------------------------------
'Actors
'----------------------------------------------------------------
Person(user, "User", "A user that sends messages and receives responses")
Container_Ext(receiver, "Communications Receiver", "container:c++", "Receives messages and sends responses. Will use a message protocol i.e. slip encapsulado en un prococolo de comunicaciones i.e: socket-tcp")

'----------------------------------------------------------------
'Components
'----------------------------------------------------------------
Boundary(comms_snd, "Communications Sender") {
    Component(comms_transport, "Transport Manager", "component:c++", "Manages basic data channels used to enable data exchange")
    Component(comms_cli, "Command Line Interface", "component:c++", "Interface between the communications sender and the user")
}

'----------------------------------------------------------------
'Relations
'----------------------------------------------------------------
Rel_R(comms_transport, receiver, "Sends data bytes arras to", "tcp socket")
Rel_R(comms_cli, comms_transport, "Sends data bytes arras to", "tcp socket")
Rel_R(user, comms_cli, "Sends messages and receives responses using", "")

Rel_L(comms_cli, user, "", "", $tags="invisible")

SHOW_LEGEND()

@enduml
