# This starter workflow is for a CMake project running on a single platform and using robot
# framework for acceptance testing.
# See: https://docs.robotframework.org/docs/using_rf_in_ci_systems/ci/github-actions
name: Run Robot Framework Tests
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  robot-framework-acceptance-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Install Readline
        run: sudo apt-get install libreadline-dev

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install additional dependencies if needed
          pip install -r requirements.txt

      - name: Run Robot Framework tests
        run: |
          if ! robot --loglevel TRACE:INFO --exclude EXCL --skip SKIP --removekeywords tag:REMOVE --flattenkeywords tag:FLAT --outputdir ./atest-results ./atest/; then
              echo "Robot Framework tests failed. Rerunning failed tests..."
              if [ -f atest-results/output.xml ]; then
                  robot --rerunfailed atest-results/output.xml --outputdir atest-results-rerun tests/ || true
                  if [ -f atest-results-rerun/output.xml ]; then
                      rebot --output atest-results/output.xml --log atest-results/log.html --report atest-results/report.html --merge atest-results/output.xml atest-results-rerun/output.xml
                  else
                      echo "No output.xml file found from rerun. Skipping merge."
                  fi
              else
                  echo "No output.xml file found. Cannot rerun failed tests."
              fi
          fi

          echo "Script execution completed"
        continue-on-error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./atest-results
          name: robot-test-results
          retention-days: 7
